### ISSUE TITLE
Support URL rewriting for static assets referenced in CSS files.

### ISSUE THREAD

**Issue by ittaibaratz** [wcm-io-frontend/aem-clientlib-generator#14]
This is related to https://github.com/adobe/aem-spa-project-archetype/issues/61

When using Create React App (And other frameworks using webpack), the static assets are automatically copied to the build folder and their URL is updated. For example, in my CSS file I have the following font family definition:

`@font-face {
    font-family: AvenirBook;
    src: url("resources/AvenirLTStd-Book.otf") format("opentype");
}`

When my app is compiled, the result CSS will have the following URL:
`src:url(/static/media/AvenirLTStd-Book.ecb0c2ae.otf)`

I can copy the static assets  to the AEM clientlib however with the resources configuration, however the URL which appears in the CSS will no longer work, as AEM needs a URL such as 
`/etc.clientlibs/mysamplespa/clientlibs/mysamplespa-react/resources/AvenirLTStd-Book.ecb0c2ae.otf`

My suggestion to resolve this is to add the ability to rewrite the CSS files through regex.
So to solve the problem above I want to be able to automatically replace "/static/media" with "/etc.clientlibs/mysamplespa/clientlibs/mysamplespa-react/resources" in the CSS files.

**Comment by stefanseifert** [comment]
thanks for the contribution, we'll have a look at the PR

**Comment by ifahrentholz** [comment]
Hi @ittaibaratz,

the purpose of the `aem-clientlib-generator` is to copy files from your dist folder into the AEM (clientlib) context and create the `*.txt` files. 

The `aem-clientlib-generator` should not be responsible for "compile" tasks like url rewriting. 
Therefore you should use tools which are designed to do just that - like `webpack`.

I've investigated a little and the `create-react-app` uses under the hood webpack and the `url-loader`.
The `url-loader` accepts the argument `publicPath` which when it's set will do exactly what you are asking for.

You can adjust these settings when you `run npm run eject ` in your CRA project.

I can imagine that you want to avoid ejecting your project. If that's so you can take a look at:

1. https://facebook.github.io/create-react-app/docs/alternatives-to-ejecting
2. Or consider using something like: https://github.com/timarney/react-app-rewired

We want to avoid making these kind of changes in `aem-clientlib-generator` since it would clash with webpack or other build-tools.

**Comment by ittaibaratz** [comment]
Thanks @ifahrentholz , I will consider your suggestions.

**Comment by kevinolivar** [comment]
Sorry for reviving this topic :-)

Got a similar issue. I am using [remixicon](https://github.com/Remix-Design/RemixIcon/issues) and aem clientlib updates my font face URL by adding 'clientlib-site/css/'

From remixicon.css
```
@font-face {
  font-family: "remixicon";
  src: url('remixicon.eot?t=1590207869815'); /* IE9*/
  src: url('remixicon.eot?t=1590207869815#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url("remixicon.woff2?t=1590207869815") format("woff2"),
  url("remixicon.woff?t=1590207869815") format("woff"),
  url('remixicon.ttf?t=1590207869815') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('remixicon.svg?t=1590207869815#remixicon') format('svg'); /* iOS 4.1- */
  font-display: swap;
}
```

From site.css (generated by aem clientlib)
```
@font-face {
  font-family: "remixicon";
  src: url('clientlib-site/css/remixicon.eot?t=1590207869815'); /* IE9*/
  src: url('clientlib-site/css/remixicon.eot?t=1590207869815#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url("clientlib-site/css/remixicon.woff2?t=1590207869815") format("woff2"),
  url("clientlib-site/css/remixicon.woff?t=1590207869815") format("woff"),
  url('clientlib-site/css/remixicon.ttf?t=1590207869815') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('clientlib-site/css/remixicon.svg?t=1590207869815#remixicon') format('svg'); /* iOS 4.1- */
  font-display: swap;
}
```

I tried rewriting the URL in webpack because AEM needs 'resources' as for public assets. However, again, clientlib appends 'clientlib-site/css' (path relative to the css file, I guess)


Is there a way to tell clientlib to not rewrite the url of specific files?
Is there good AEM practice to import third party fonts without having to copy and extract bits (eg. font-face) of the third party package?

Thanks.

**Comment by ifahrentholz** [comment]
@kevinolivar, @ittaibaratz: Did you try to use the "base" configuration of clientlib generator ?

What you can try is to copy your whole "static" or "dist" bundle into resources and resolve the entrypoints via the base configuration.

Example:
```
assets: {
  js: {
    base: "resources",
    cwd: `../apps/dist`,
    files: ["**/runtime~main.js", "**/vendors.js", "**/main.js"],
    flatten: false,
  },
  css: {
    base: "resources",
    cwd: `../apps/dist`,
    files: ["**/main.css"],
    flatten: false,
  },
  resources: {
    cwd: `../apps/dist`,
    files: ["**/*.js", "**/*.js.LICENSE", "**/*.css"],
    flatten: false,
    ignore: [
      "**/runtime~main.js",
      "**/vendors.js",
      "**/main.js",
      "**/main.css",
    ],
  },
},
```

With this configuration it should be possible for your bundle to resolve your assets correctly.

**Comment by ifahrentholz** [comment]
Hi @ittaibaratz, Hi @kevinolivar,
please try to copy your whole bundle to the resources folder (do not flatten).
Then you should be able to configure the clientlib generator to resolve your css and js via the base configuration.
Doing this should keep your asset refs as you defined them in your original build and be resolvable.

### Example:
```
assets: {
  js: {
    base: "resources",
    cwd: `path/to/dist`,
    files: ["**/*.js"],
    flatten: false,
  },
  css: {
    base: "resources",
    cwd: `path/to/dist`,
    files: ["**/*.css"],
    flatten: false,
  },
  resources: {
    cwd: `path/to/dist`,
    files: ["**/*.*"],
    flatten: false,
    ignore: ["**/*.js", "**/*.css"],
  },
},
```

**Comment by ifahrentholz** [comment]
I'll close this issue since there is no response.

**Comment by kevinolivar** [comment]
Hi @ifahrentholz,

yeah sorry for that. Actually, I solved that by doing pretty much that but via webpack. Eg. copying the font into the resources folder.

I may give it a shot with the 'base' option of the clientlib generator.

Thanks anyway!
